In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split
import cv2
import time
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

In [3]:
happy_dataset=np.load('imgdataset\Happy.npy')
sad_dataset=np.load('imgdataset\Sad.npy')
#angry_dataset=np.load('imgdataset\Angry.npy')
print(happy_dataset.shape)
print(sad_dataset.shape)
#print(angry_dataset.shape)

(1000, 30000)
(1000, 30000)


In [4]:
whole_dataset=np.concatenate((sad_dataset,happy_dataset))

In [5]:
pd.DataFrame(whole_dataset).shape

(2000, 30000)

In [6]:
Y_dataset=np.zeros((2000,1))
Y_dataset[1000:,0]=1
Y_dataset[:1000,0]=0
print(Y_dataset.shape)

(2000, 1)


In [7]:
x_train,x_test,y_train,y_test=train_test_split(whole_dataset,Y_dataset,test_size=0.2,shuffle=True)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)
print(y_train.shape)

(1600, 30000) (1600, 1) (400, 30000) (400, 1)
(1600, 1)


In [18]:
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
cap=cv2.VideoCapture(0)
face_data=[]
i=0
predict=[]
while True:
    time.sleep(0.01)
    ret,frame=cap.read()
    if not ret:
        continue

    

    faces=face_cascade.detectMultiScale(frame,1.3,5)
    faces=sorted(faces,key=lambda x:x[2]*x[3],reverse=True)
    faces=faces[:1]
    for face in faces:
        x,y,w,h=face
        face_selection=frame[y:y+h,x:x+w]
        face_selection=cv2.resize(face_selection,(100,100))
        face_selection=np.array(face_selection)
        face_selection=face_selection.reshape(1,-1)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),5)
        cv2.putText(frame,str(''),(x+w,y+h),cv2.FONT_HERSHEY_COMPLEX,0.9,(255,0,0),1)
        face_data.append(face_selection)
        face_data_array=np.array(face_data[i])
        face_data_array=face_data_array.reshape((1,100,100,3))
        print((model.predict(face_data_array.reshape(1,100,100,3))[0][0]))
        predict=model.predict(face_data_array.reshape(1,100,100,3))
        print(predict)
        if model.predict(face_data_array.reshape(1,100,100,3))[0][0]>model.predict(face_data_array.reshape(1,100,100,3))[0][1]:
            cv2.putText(frame,str('Sad'),(x,y),cv2.FONT_HERSHEY_COMPLEX,0.9,(255,0,0),1)
        else:
            cv2.putText(frame,str('Happy'),(x,y),cv2.FONT_HERSHEY_COMPLEX,0.9,(255,0,0),1)
        i+=1
       

    cv2.imshow('Feed',frame)
    key=cv2.waitKey(1)
    if key & 0xFF==ord('q'):
        break		

cap.release()
cv2.destroyAllWindows() 

0.11246193
[[0.11246193 0.8875381 ]]
0.17005512
[[0.17005512 0.82994485]]
0.09959932
[[0.09959932 0.90040064]]
0.099432915
[[0.09943292 0.9005671 ]]
0.035033096
[[0.0350331  0.96496695]]
0.049837515
[[0.04983751 0.9501625 ]]
0.036768697
[[0.0367687 0.9632313]]
0.10291175
[[0.10291175 0.8970883 ]]
0.08245809
[[0.08245809 0.9175419 ]]
0.05002898
[[0.05002898 0.949971  ]]
0.04858885
[[0.04858885 0.9514111 ]]
0.03531935
[[0.03531935 0.9646806 ]]
0.05588404
[[0.05588404 0.94411594]]
0.050311767
[[0.05031177 0.94968826]]
0.029643476
[[0.02964348 0.9703565 ]]
0.062910154
[[0.06291015 0.93708986]]
0.10639787
[[0.10639787 0.89360213]]
0.08427185
[[0.08427185 0.9157281 ]]
0.16523086
[[0.16523086 0.83476907]]
0.2418191
[[0.2418191  0.75818086]]
0.26806793
[[0.26806793 0.7319321 ]]
0.5890504
[[0.5890504  0.41094962]]
0.5540584
[[0.5540584 0.4459416]]
0.4306817
[[0.4306817  0.56931823]]
0.670646
[[0.670646 0.329354]]
0.43278843
[[0.43278843 0.5672115 ]]
0.29307786
[[0.29307786 0.7069221 ]]
0.441878

0.4989227
[[0.4989227 0.5010773]]
0.5762409
[[0.5762409 0.4237592]]
0.74398357
[[0.74398357 0.25601646]]
0.5625004
[[0.5625004  0.43749958]]
0.6211174
[[0.6211174 0.3788826]]
0.63627255
[[0.63627255 0.36372745]]
0.7226247
[[0.7226247  0.27737525]]
0.70900124
[[0.70900124 0.29099876]]
0.5296208
[[0.5296208  0.47037914]]
0.7253806
[[0.7253806  0.27461943]]
0.74429923
[[0.74429923 0.2557008 ]]
0.6552266
[[0.6552266  0.34477335]]
0.5073892
[[0.5073892 0.4926108]]
0.54039663
[[0.54039663 0.45960334]]
0.7589098
[[0.7589098  0.24109021]]
0.73797655
[[0.73797655 0.2620235 ]]
0.7942977
[[0.7942977  0.20570232]]
0.6625427
[[0.6625427  0.33745736]]
0.6499629
[[0.6499629  0.35003707]]
0.7731446
[[0.7731446  0.22685546]]
0.3623528
[[0.3623528  0.63764715]]
0.3922887
[[0.3922887 0.6077113]]
0.36232802
[[0.36232802 0.63767195]]
0.5359233
[[0.5359233  0.46407664]]
0.6035533
[[0.6035533 0.3964467]]
0.7579389
[[0.7579389  0.24206111]]
0.6183544
[[0.6183544  0.38164556]]
0.8187735
[[0.8187735  0.18122652

In [9]:
#from keras.layers import Conv2D,Dense,Activation,MaxPool2D,Flatten
#from keras.models import Sequential
from keras.utils import to_categorical
import keras

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
c:\users\ritik\appdata\local\programs\python\python37\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [10]:
YY_train=to_categorical(y_train)
print(YY_train.shape)
YY_test=to_categorical(y_test)
print(YY_test.shape)

(1600, 2)
(400, 2)


In [11]:
model=models.Sequential()

model.add(layers.Conv2D(3,(3,3),input_shape=(100,100,3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPool2D((2,2)))
    
model.add(layers.Conv2D(3,(3,3),input_shape=(100,100,3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPool2D((2,2)))

model.add(layers.Conv2D(3,(3,3),input_shape=(100,100,3)))
model.add(layers.Activation('relu'))
model.add(layers.MaxPool2D((2,2)))
    

    
model.add(layers.Flatten())
model.add(layers.Dense(100))
model.add(layers.Activation('sigmoid'))
model.add(layers.Dense(2))
model.add(layers.Activation('softmax'))

    
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 98, 98, 3)         84        
_________________________________________________________________
activation (Activation)      (None, 98, 98, 3)         0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 49, 49, 3)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 47, 47, 3)         84        
_________________________________________________________________
activation_1 (Activation)    (None, 47, 47, 3)         0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 23, 23, 3)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 21, 21, 3)         8

In [12]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [13]:
xx_train=x_train.reshape((1600,100,100,3))
print(xx_train.shape)
xx_test=x_test.reshape((400,100,100,3))
print(xx_test.shape)

(1600, 100, 100, 3)
(400, 100, 100, 3)


In [14]:
model.fit(xx_train,y_train,
         shuffle=True,
         epochs=10,
         batch_size=160,
         validation_data=(xx_test,y_test))

Train on 1600 samples, validate on 400 samples
Epoch 1/10
1600/1600 [==============================] - 3s 2ms/sample - loss: 0.5255 - accuracy: 0.8125 - val_loss: 0.4220 - val_accuracy: 0.9200
Epoch 2/10
1600/1600 [==============================] - 2s 1ms/sample - loss: 0.3682 - accuracy: 0.9506 - val_loss: 0.2978 - val_accuracy: 0.9675
Epoch 3/10
1600/1600 [==============================] - 2s 1ms/sample - loss: 0.2591 - accuracy: 0.9656 - val_loss: 0.1936 - val_accuracy: 0.9875
Epoch 4/10
1600/1600 [==============================] - 2s 1ms/sample - loss: 0.1694 - accuracy: 0.9819 - val_loss: 0.1222 - val_accuracy: 0.9900
Epoch 5/10
1600/1600 [==============================] - 2s 1ms/sample - loss: 0.1079 - accuracy: 0.9937 - val_loss: 0.0778 - val_accuracy: 0.9975
Epoch 6/10
1600/1600 [==============================] - 2s 1ms/sample - loss: 0.0703 - accuracy: 0.9969 - val_loss: 0.0541 - val_accuracy: 1.0000
Epoch 7/10
1600/1600 [==============================] - 2s 1ms/sample - loss: